spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: 0.0.0.0/0
      port: 27017
      authentication-database: admin
      username: bodari32
      password: RecommenDiary
      database: dbfpk
      # uri: mongodb+srv://bodari32:<db_password>@cluster0.dbfpk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error